# This is the configuration file for the pre-commit framework, a simple way to
# run git hooks automatically. See https://pre-commit.com/index.html for
# details.
default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
    # These directories contains broken files, failures are expected
    exclude: "TLS-Core/src/test/resources/workflow_trace_serialization_tests-(positive|negative)/.+\\.xml"
  - id: check-yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: no-commit-to-branch
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: ["--ignore-words=.codespellignore"]
    exclude: ".*\\.pem"
